version: '3'

services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vod
    volumes:
      - postgres:/var/lib/postgresql/data/

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:latest
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 5051:5051
    environment:
      PGADMIN_DEFAULT_EMAIL: local@local.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 5051
    volumes:
      - pgadmin:/var/lib/pgadmin

  hono-server:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./apps/hono-server/Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 3002:3002
    env_file: ./.env

  tests:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true

volumes:
  postgres:
  pgadmin:
